name: pull-request-test

on: [pull_request]

jobs:
  pull-request-test:
    runs-on: ubuntu-latest
    steps:
      - name: build for test
        uses: docker/build-push-action@v2
        with:
          push: false